### ISSUE TITLE
Skill issue cope FR innit bruv

### ISSUE THREAD

**Issue by Vandemonica** [Alpha-craft/learn-nodejs#1]
![](https://media.tenor.com/wMFOzCKEr-kAAAAC/suisei-skill-issue.gif)

Kok nggak pakai laravel bang?

**Comment by Alpha-craft** [comment]
![](https://media.tenor.com/NCQy6_eX1mIAAAAC/hologra-hololive.gif)
Siapa yang nyuruh kamu tanya begitu
